### ISSUE TITLE
PaddleSpeech语音合成

### ISSUE THREAD

**Issue by zz1997361** [Kedreamix/PaddleAvatar#3]
语音合成中选择PWGan，输入文本内容无效，合成的语音内容仍然是“你好，我是数字人分身，很高兴认识大家！”；在高质量男声音色中，支持输入文本内容，是bug还是仅支持？

**Comment by Kedreamix** [comment]
应该是没有合成到，具体看报错，应该是对应的编码解码不正确应该，可能没有对应模型
