### ISSUE TITLE
 报这个错误。。No such file or directory: 'img/PaddleAvator.png'

### ISSUE THREAD

**Issue by tete3421** [Kedreamix/PaddleAvatar#6]
用的conda环境，项目根目录执行的网页部署，然后加载这个图片的时候就这样了，图片地址是存在的··

**Comment by Kedreamix** [comment]
是不是运行不是当前目录运行的

**Comment by tete3421** [comment]
我知道了，你的项目里 加载 这个图片的 写是的 img/PaddleAvator.png，但是实际图片名字应该是img/PaddleAvatar.png,名字对应不上所以找不到···· 一个o一个a

**Comment by Kedreamix** [comment]
soga，那就是我疏忽了害，我会改一下的
